service: serverless-example
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2

functions:
  event-producer:
    handler: event-producer/index.handler
    events:
      - http: 
          path: events
          method: post
    iamRoleStatements:
      Effect: Allow
      Action:
        - sqs:ListQueues
        - sqs:SendMessageBatch
        - sqs:SendMessage
        - sqs:GetQueueAttributes
      Resource: "*"

  event-consumer: 
    handler: event-consumer/index.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - eventQueue
              - Arn
          batchSize: 10
    iamRoleStatements:
      Effect: Allow

resources:
  Resources:
    eventQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: events
